spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgresme
    username: postgres
    password: pass

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path : /api-docs

jwt:
  secret: ZSCh9kkZU7I4/O9v3bau5TE3VrtfqB/oComvw/zKEXp0CD6gavnRCJ+70MZJzNLF
  lifetime: 30m